In [1]:
import warnings
warnings.filterwarnings("ignore")
from pathlib import Path
import pandas as pd

In [2]:
current_dir = Path.cwd()
work_dir = current_dir.parent.parent
data_dir = f'{work_dir}/data'

# Dataset
######  Refined NHANES 2007-2012 spirometry dataset for the comparison of segmented (piecewise) linear models to that of GAMLSS
 
Downloaded from : https://data.mendeley.com/datasets/dwjykg3xww/1


[1] Zavorsky, Gerald (2024), “Refined NHANES 2007-2012 spirometry dataset for the comparison of segmented (piecewise) linear models to that of GAMLSS”, Mendeley Data, V1, doi: 10.17632/dwjykg3xww.1

### Dataset  Overview
(based on information provided on dataset website on Mendeley)

| Feature | Detail/Range | Notes |
| :--- | :--- | :--- |
| **Data Source** | National Health and Nutrition Examination Survey (NHANES) | Secondary data utilization. |
| **Survey Years** | 2007 - 2012 | Period of NHANES data used. |
| **Initial Participants** | 31,451 | Total participants in the initial NHANES pool. |
| **Refined Participants (Spirometry)** | **16,596** | Participants meeting technical quality standards. |
| **Age Range** | 6 - 80 years | Age of included participants. |
| **Racial/Ethnic Backgrounds** | Diverse | Study represents various racial and ethnic groups. |
| **Weight Range** | 16.4 - 218.2 kg | Range of participant weights. |
| **Height Range** | 104.6 - 203.8 cm | Range of participant heights. |
| **BMI Range** | 12.5 - 84.9 kg/m² | Range of participant Body Mass Index. |
| **Spirometry Quality Standard** | American Thoracic Society (2005) | Minimum technical quality standards (A and B maneuvers). |
| **Secondary Analysis** | Z-scores, Restrictive Pattern, Airway Obstruction | Calculated from GAMLSS and piecewise regression models using Lower Limit of Normal (LLN). |

In [3]:
file_name = "NHANES_2007_2012_Only_Acceptable_Spirometry_Values.csv"

In [4]:
df = pd.read_csv(f"{data_dir}/{file_name}")
df.head()

,SEQN,Sex,Race,Age,LnAge,Age2,Age3,Age_Groups,Height2_x_Race,Weight,...,LLN_FVC_5th_Segmented,LLN_FVC_2point5_Segmented,FEV1_FVC_Ratio_ULN_95th_Segmented,FEV1_FVC_Ratio_ULN_97point5_Segmented,FVC_ULN_95th_Segmented,FVC_ULN_97point5_Segmented,Baseline_FVC_Quality,Baseline_FEV1_Quality,Baseline_Number_Acceptable_Curves,Baseline_Effort_Quality
0,41475,Female,"Other race, including multi-racial",62.50,4.135167,3906.2500,244140.625000,60-69 yrs,95728.36,138.9,...,No,No,no,no,No,No,Exceeds ATS data collection standards: 3 accep...,Exceeds ATS data collection standards: 3 acce...,3,All 6 spirometry quality curves are acceptable
1,41476,Female,"Other race, including multi-racial",6.75,1.909543,45.5625,307.546875,6-9 yrs,57984.64,22.0,...,No,No,no,no,Yes,No,Exceeds ATS data collection standards: 3 accep...,Exceeds ATS data collection standards: 3 acce...,8,All 6 spirometry quality curves are acceptable
2,41479,Male,Mexican American,52.50,3.960813,2756.2500,144703.125000,50-59 yrs,47678.72,65.7,...,No,No,no,no,No,No,Exceeds ATS data collection standards: 3 accep...,Exceeds ATS data collection standards: 3 acce...,5,All 6 spirometry quality curves are acceptable
3,41481,Male,Black,21.25,3.056357,451.5625,9595.703125,20-29 yrs,33379.29,77.9,...,No,No,no,no,No,No,Exceeds ATS data collection standards: 3 accep...,Exceeds ATS data collection standards: 3 acce...,7,All 6 spirometry quality curves are acceptable
4,41482,Male,Mexican American,64.75,4.170534,4192.5625,271468.421875,60-69 yrs,60412.88,101.6,...,No,No,no,no,No,No,Meets ATS data collection standards: 3 accepta...,Exceeds ATS data collection standards: 3 acce...,7,All 6 spirometry quality curves are acceptable

In [5]:
# Check columns in the dataset
df.columns

Index(['SEQN', 'Sex', 'Race', 'Age', 'LnAge', 'Age2', 'Age3', 'Age_Groups',
       'Height2_x_Race', 'Weight', 'Height', 'LnHeight', 'Height2',
       'Age_Height', 'Age_Height2', 'BMI', 'Baseline_FEV1_L', 'Baseline_FVC_L',
       'Baseline_FEV1_FVC_Ratio', 'Baseline_PEF_Ls', 'Baseline_FEF2575_Ls',
       'Baseline_Extrapolated_Volume', 'Baseline_Forced_Expiratory_Time',
       'FEV1_FVC_ratio_GLOBAL_Zscores', 'FEV1_Zscores_GLOBAL',
       'FVC_Zscores_GLOBAL', 'FEV1_ULN_GLOBAL', 'Ratio_Zscores_GAMLSS',
       'FVC_Zscores_GAMLSS', 'FEV1_Zscores_GAMLSS', 'Ratio_Zscores_Linear',
       'FEV1_Zscores_Segmented', 'FVC_Zscores_Segmented',
       'Normal_5th_Segmented', 'Normal_5th_GAMLSS', 'Normal_2point5_Segmented',
       'Normal_2point5_GAMLSS', 'Obstruction_5th_Segmented',
       'Obstruction_5th_GAMLSS', 'Obstruction_2point5_Segmented',
       'Obstruction_2point5_GAMLSS',
       'Restrictive_Spirometry_Pattern_5th_Segmented',
       'Restrictive_Spirometry_Pattern_5th_GAMLSS',
       'Restrictive_Spirometry_Pattern_2point5_Segmented',
       'Restrictive_Spirometry_Pattern_2point5_GAMLSS', 'PRISm_Segmented_5th',
       'PRISm_GAMLSS_5th', 'PRISm_Segmented_2point5', 'PRISm_GAMLSS_2point5',
       'Mixed_5th_Segmented', 'Mixed_5th_GAMLSS', 'Mixed_2point5_Segmented',
       'Mixed_2point5_GAMLSS', 'OneVariable_LLN_5th_Segmented',
       'OneVariable_LLN_5th_GAMLSS', 'OneVariable_LLN_2point5_Segmented',
       'OneVariable_LLN_2point5_GAMLSS', 'LLN_FEV1_5th_Segmented',
       'LLN_FEV1_5th_GAMLSS', 'LLN_FEV1_2point5_Segmented',
       'LLN_FEV1_2point5_GAMLSS', 'LLN_Ratio5th_Linear',
       'LLNRatio2point5_Linear', 'LLN_FVC_5th_Segmented',
       'LLN_FVC_2point5_Segmented', 'FEV1_FVC_Ratio_ULN_95th_Segmented',
       'FEV1_FVC_Ratio_ULN_97point5_Segmented', 'FVC_ULN_95th_Segmented',
       'FVC_ULN_97point5_Segmented', 'Baseline_FVC_Quality',
       'Baseline_FEV1_Quality', 'Baseline_Number_Acceptable_Curves',
       'Baseline_Effort_Quality'],
      dtype='object')

### Initial Observation of data

 - Demographic Data

| Category | Variables | Notes |
| :--- | :--- | :--- |
| **Age-related** | Age, LnAge, Age², Age³ | Includes transformations (natural log and polynomial). |
| **Anthropometrics** | Height, LnHeight, Height², Weight, BMI | Body size and composition measurements. |
| **Interaction Terms** | Age_Height, Age_Height², Height² x Race | Used for statistical modeling. |
| **Categorical** | Race, Sex, Age_Groups | Variables used for grouping or classification. |

- Statistical Modeling Variables

| Category | Variables | Type/Use |
| :--- | :--- | :--- |
| **Response Variables** | FEV1, FVC, FEV1/FVC | Dependent variables; main outcomes of interest. |
| **Fixed Effects** | Age, Sex, Height, Race | Variables whose effects are assumed constant across the population. |
| **Random Effects** | Age_Groups, Survey_Wave | Variables with effects that may vary or are sampled from a larger population (common in mixed-effects models). |


NB: 
- Forced Expiratory Volume in 1 s ( **FEV1** ): Air exhaled forcefully in **one second**. 
- Forced Vital Capacity (**FVC**): **Total** air exhaled during a forced breath.
- FEV1/FVC Ratio (**FEV1/FVC**): Ratio for diagnosing **airflow obstruction**. 

###### Baseline Measurements ()Raw Spirometry data)
- Baseline_FEV1_L
- Baseline_FVC_L
- Baseline_FEV1_FVC_Ratio
- Baseline_PEF_Ls
- Baseline_FEF2575_Ls

In [6]:
# Saaving the demographic_data and target-variable separatedly for statistical analysis

demographic_data = ['Age', 'LnAge', 'Age2', 'Age3',
 'Sex', 'Race',
 'Height', 'LnHeight', 'Height2',
 'Weight', 'BMI',
 'Height2_x_Race',
 'Age_Height', 'Age_Height2']

target_variables = ['Baseline_FEV1_L',
 'Baseline_FVC_L',
 'Baseline_FEV1_FVC_Ratio']

selected_columns = demographic_data + target_variables
new_df = df[selected_columns]
new_df.head()

,Age,LnAge,Age2,Age3,Sex,Race,Height,LnHeight,Height2,Weight,BMI,Height2_x_Race,Age_Height,Age_Height2,Baseline_FEV1_L,Baseline_FVC_L,Baseline_FEV1_FVC_Ratio
0,62.50,4.135167,3906.2500,244140.625000,Female,"Other race, including multi-racial",154.7,5.041488,23932.09,138.9,58.04,95728.36,9668.750,1.495756e+06,2.025,2.473,0.818844
1,6.75,1.909543,45.5625,307.546875,Female,"Other race, including multi-racial",120.4,4.790820,14496.16,22.0,15.18,57984.64,812.700,9.784908e+04,1.551,1.742,0.890356
2,52.50,3.960813,2756.2500,144703.125000,Male,Mexican American,154.4,5.039547,23839.36,65.7,27.56,47678.72,8106.000,1.251566e+06,2.957,3.545,0.834133
3,21.25,3.056357,451.5625,9595.703125,Male,Black,182.7,5.207845,33379.29,77.9,23.34,33379.29,3882.375,7.093099e+05,4.541,4.928,0.921469
4,64.75,4.170534,4192.5625,271468.421875,Male,Mexican American,173.8,5.157905,30206.44,101.6,33.64,60412.88,11253.550,1.955867e+06,2.920,3.907,0.747377

In [7]:
new_df.shape

(16596, 17)

In [8]:
# Save
new_df.to_csv(f"{data_dir}/selected_df.csv", index=False)

Statistic Analysis follows in another Notebook: **02_statistical Analysis**